M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Tue Sep 29 09:56:42 2026
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-29T09:56:42+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X105.95Y-107.9
X108.33Y-106.85
T2
X101.29Y-111.1
X103.83Y-111.1
X106.37Y-111.1
X108.91Y-111.1
M30
